server:
  port: 8054

spring:
  application:
    name: MyApp
  data:
    mongodb:
      database: mytestdb
      uri: mongodb://localhost:27017

logging.level.org:
  springframework.web: DEBUG

management:
  endpoints:
    enabled-by-default: true
    info:
      enabled: true



restUri: http://localhost:8090/v1/getRestResponseEntity