server:
  port: 8054

spring:
  application:
    name: MyApp
  data:
    jpa:
      show-sql: true
    mongodb:
      database: mytestdb
      uri: mongodb://localhost:27017


spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true




logging.level.org:
  springframework.: DEBUG
  com.myapp.ItemService: INFO
  hibernate.SQL: INFO
management:
  endpoints:
    enabled-by-default: true
    info:
      enabled: true






restUri: http://localhost:8090/v1/getRestResponseEntity